smartparking/smartparking/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
]

smartparking/system/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static

app_name = "Admin"

urlpatterns = [
    path('',index,name="home"),
    path('register/',register,name="register"),
    path('aboutus/',aboutus,name="aboutus"),
    path('contactus/',contactus,name="contactus"),
    path('howitworks',howitworks,name="howitworks"),
    path('faqs',faqs,name="faqs"),
    path('orders/', orders, name="orders"),
    path('aboutus/', aboutus, name="aboutus"),
    path('login/', login, name="login"),
    path('adminregistration/',adminregistration,name="adminregistration"),
    path('adminlogin/',adminlogin,name="adminlogin"),
    path('userregistration/', userregistration, name="userregistration"),
    path('userlogin/', userlogin, name="userlogin"),
    path('userdashboard/', userdashboard, name="userdashboard"),
    path('userorders/', userorders, name="userorders"),
    path('admindashboard/',admindashboard, name = "admindashboard"),
    path('parkingarea/',viewparkingareas, name = "parkingarea"),
    path('addparkingarea/',addparkingarea, name="addparkingarea"),
    path('aboutparkingarea/<int:parking_id>/', aboutparkingarea, name = "aboutparkingarea"),
    path('success/', OrderSuccess, name = "OrderSuccess"),
    path('checkout/', checkout, name = "checkout"),
    path('adminfreeslots/<int:parking_id>/',adminfreeslots, name = "adminfreeslots"),
    path('freed/<int:order_id>/',freed, name= "freed"),
    path('adminaboutparkingarea/<int:parking_id>/', adminaboutparkingarea, name = "adminaboutparkingarea"),
    path('logout/',logout_view,name="logout"),
]

smartparking/system/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=10)
    address = models.TextField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return self.first_name + " " + self.last_name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=10)
    age = models.IntegerField()

    def __str__(self):
        return self.first_name + " " + self.last_name

class Parking_area(models.Model):
    admin_id = models.ForeignKey(Admin,on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    location = models.CharField(max_length=50)
    number_of_parking_slots = models.IntegerField()
    opening_time = models.TimeField()
    closing_time = models.TimeField()
    base = models.IntegerField()
    tariff = models.FloatField()
    def __str__(self):
        return self.name

#class Parking_slot(models.Model):
#   parking_slot_id = models.IntegerField()
#    parking_area_id = models.ForeignKey(Parking_area,on_delete=models.CASCADE)
#    status = models.BooleanField(default=True)
#    start_time = models.TimeField()
#    end_time = models.TimeField()
#
#    def __str__(self):
#        return self.parking_slot_id

class Orders(models.Model):
    parking_area_id = models.ForeignKey(Parking_area,on_delete=models.CASCADE)
    #parking_slot_id = models.ForeignKey(Parking_slot,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    vehicle_number = models.CharField(max_length=10)
    starting_time = models.DateTimeField(null = True,blank=True)
    ending_time = models.DateTimeField(null = True,blank=True)
    status = models.BooleanField(default=True)
    #date = models.DateField(null=True)

smartparking/system/forms.py
from django import forms
from django.db import models
from .models import *


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter username'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter email'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'enter password'}),
        }
        
class AdminForm(forms.ModelForm):
    class Meta:
        model = Admin
        fields = ('first_name', 'last_name', 'phone_number', 'address', 'age')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter First name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter last name'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter phone number'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'enter address'}),
            'age':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter age'})
        }

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('first_name','last_name','phone_number','age')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter First name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter last name'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter phone number'}),
            'age': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter age'})
        }


class ParkingAreaForm(forms.ModelForm):
    class Meta:
        model = Parking_area
        fields = '__all__'
        exclude = ('admin_id',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','placeholder': 'enter name'}),
            'location': forms.TextInput(attrs={'class': 'form-control','placeholder': 'enter address'}),
            'opening_time': forms.TimeInput({'class': 'form-control','placeholder': 'enter opening time'}),
            'closing_time': forms.TimeInput({'class': 'form-control', 'placeholder': 'enter closing time'}),
        }

smartparking/system/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.core.exceptions import ValidationError
from .forms import *
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as user_login   
from django.contrib.auth.decorators import login_required
from datetime import timedelta
import datetime, time
import pytz
import pickle
import os

# Create your views here.
def index(request):
    return render(request, 'system/index.html', {})

def orders(request):
    orders = Orders.objects.filter(customer=request.session['user_id'])
    return render(request,'system/orders.html',{'orders':orders})

def register(request):
    return  render(request, 'system/register.html', {})

def aboutus(request):
    return  render(request, 'system/about-us.html', {})

def contactus(request):
    return  render(request, 'system/contact-us.html', {})

def faqs(request):
    return  render(request, 'system/faqs.html', {})

def howitworks(request):
    return  render(request, 'system/how-it-works.html', {})

def login(request):
    return render(request, 'system/login.html', {})


def userorders(request):
    return HttpResponse("userorders")



def adminlogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                user_login(request,user)
                print(user.pk)
                request.session['admin_id']=Admin.objects.filter(user_id = user.pk).first().id
                return HttpResponseRedirect(reverse('Admin:admindashboard'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponse("INvalid Details")

    else:
        return render(request,'system/adminlogin.html',{})

def adminregistration(request):
    registered = False
    if(request.method == "POST"):
        user_form = UserForm(data=request.POST)
        admin_form = AdminForm(data=request.POST)

        if(user_form.is_valid() and admin_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            admin = admin_form.save(commit=False)
            admin.user = user
            admin.save()
            registered = True
            return HttpResponseRedirect(reverse('Admin:adminlogin'))
        else:
            print(user_form.errors, admin_form.errors)
    else:
        user_form = UserForm()
        admin_form = AdminForm()
    return render(request, 'system/adminregistration.html', {'user_form': user_form, 'admin_form': admin_form, 'registered': registered})


def userregistration(request):
    registered = False
    if(request.method == "POST"):
        user_form = UserForm(data=request.POST)
        admin_form = CustomerForm(data=request.POST)

        if(user_form.is_valid() and admin_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            admin = admin_form.save(commit=False)
            admin.user = user
            admin.save()
            registered = True
            return HttpResponseRedirect(reverse('Admin:userlogin'))
        else:
            print(user_form.errors, admin_form.errors)
    else:
        user_form = UserForm()
        admin_form = CustomerForm()
    return render(request, 'system/userregistration.html', {'user_form': user_form, 'admin_form': admin_form, 'registered': registered})

def userlogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                user_login(request,user)
                request.session['user_id'] = Customer.objects.filter(
                    user_id=user.pk).first().id
                return HttpResponseRedirect(reverse('Admin:userdashboard'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponse("INvalid Details")

    else:
        return render(request, 'system/userlogin.html', {})


def admindashboard(request):
    admindetails = Admin.objects.filter(id = request.session['admin_id']).first()
    parkingarea = Parking_area.objects.filter(admin_id = request.session['admin_id'])
    if(admindetails == None):
        return HttpResponse("<h1> HACKER!!! <h1>")
    context = {
        'admindetails' : admindetails,
        'parkingarea' : parkingarea
    }
    return render(request, 'system/admindashboard.html', context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('Admin:home'))

def userdashboard(request):
    userdetails = Customer.objects.filter(id=request.session['user_id']).first()
    if(userdetails == None):
        return HttpResponse("<h1> HACKER!!! <h1>")
    context = {
        'userdetails': userdetails
    }
    return render(request, 'system/userdashboard.html', context)

def addparkingarea(request):
    if request.method == 'POST':
        form = ParkingAreaForm(data=request.POST)
        if form.is_valid():
            object1 = form.save(commit=False)
            # request.id is the primary key of the owner ( I'm not sure how to get primary key from owner here.)
            object1.admin_id = Admin.objects.get(id=request.session['admin_id'])
            #object1.number_of_parking_slots = 5
            object1.save()
            with open(os.path.join(os.path.dirname(__file__), 'filename.pickle'), 'rb') as handle:
                dict1 = pickle.load(handle)
            dict1[str(object1.id)] =  [True for i in range(0,object1.number_of_parking_slots)]
            with open(os.path.join(os.path.dirname(__file__), 'filename.pickle'), 'wb') as handle:
                pickle.dump(dict1, handle, protocol=pickle.HIGHEST_PROTOCOL)
            return HttpResponseRedirect(reverse('Admin:admindashboard'))
    else:
        form = ParkingAreaForm()
    return render(request, 'system/addparkingarea.html', {'form': form})


def viewparkingareas(request):
    parkingarea = Parking_area.objects.all()
    context = {
        'parkingarea' : parkingarea,
    }   
    return render(request, 'system/parkingarea.html', context)

def aboutparkingarea(request, parking_id):
    request.session['pid'] = str(parking_id)
    parkingarea = Parking_area.objects.filter(id = parking_id)
    with open(os.path.join(os.path.dirname(__file__), 'filename.pickle'), 'rb') as handle:
        dict1 = pickle.load(handle)
    print(dict1)
    context = {
        'parkingarea' : parkingarea,
        'list' : dict1[str(parking_id)],
    }
    return render(request, 'system/aboutparkingarea.html', context)

def adminaboutparkingarea(request, parking_id):
    request.session['pid'] = str(parking_id)
    parkingarea = Parking_area.objects.filter(id = parking_id)
    with open(os.path.join(os.path.dirname(__file__), 'filename.pickle'), 'rb') as handle:
        dict1 = pickle.load(handle)
    context = {
        'parkingarea' : parkingarea,
        'list' : dict1[str(parking_id)],
    }
    return render(request, 'system/adminaboutparkingarea.html', context)

def getstarttime(request):
    date_time = request.session['entry-time']
    date_time = datetime.datetime.strptime(date_time, "%Y-%m-%dT%H:%M")
    date_time = pytz.timezone('Asia/Kolkata').localize(date_time, is_dst=None)
    return date_time

def getexittime(request):
    date_time = request.session['exit-time']
    date_time = datetime.datetime.strptime(date_time, "%Y-%m-%dT%H:%M")
    date_time = pytz.timezone('Asia/Kolkata').localize(date_time, is_dst=None)
    return date_time

def check_availability(request):
    
    date_time = getstarttime(request)
    today = date_time.date()
    orders = Orders.objects.all().order_by('starting_time').order_by('ending_time').filter(starting_time__date = today).filter(status=True)
    end_time = getexittime(request)
    x = date_time
    parkingarea = Parking_area.objects.get(pk = request.session['pid'])
    while(x <= end_time):
        tmp = orders.filter(starting_time__lte = x).filter(ending_time__gte = x)
        if(len(tmp) >= parkingarea.number_of_parking_slots):
            return False
        x += timedelta(minutes = 1)

    openingtime = datetime.datetime.combine(today, parkingarea.opening_time)
    openingtime = pytz.timezone('Asia/Kolkata').localize(openingtime, is_dst=None)
    closingtime = datetime.datetime.combine(today, parkingarea.closing_time)
    closingtime = pytz.timezone('Asia/Kolkata').localize(closingtime, is_dst=None)
    
    if(openingtime <= date_time and date_time <= closingtime and openingtime <= end_time and end_time <= closingtime and date_time.date() >= datetime.date.today()):
        return True
    else:
        return False


def checkout(request):
    request.session['entry-time'] = request.POST['entry-time']
    request.session['exit-time'] = request.POST['exit-time']
    with open(os.path.join(os.path.dirname(__file__), 'filename.pickle'), 'rb') as handle:
        dict1 = pickle.load(handle)
    print(dict1)
    with open(os.path.join(os.path.dirname(__file__), 'filename.pickle'), 'wb') as handle:
        pickle.dump(dict1, handle, protocol=pickle.HIGHEST_PROTOCOL)
    print(dict1[str(request.session['pid'])])
    possible = check_availability(request)
    
    context = {
        'possible' : possible
    }
    return render(request, 'system/checkout.html', context)

def OrderSuccess(request):
    if(check_availability(request)):
        with open(os.path.join(os.path.dirname(__file__), 'filename.pickle'), 'rb') as handle:
            dict1 = pickle.load(handle)
        for i in range(0, len(dict1[str(request.session['pid'])])):

smartparking/system/templates/system/adminlogin.html
{% extends 'system/base.html' %}
{% block head %}
<link rel="shortcut icon" href="/assets/images/logo/new_logo2.jpg">
<link rel="apple-touch-icon" href="/assets/images/logo/apple-touch-icon.png">

<link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css">

<link rel="stylesheet" href="/assets/vendors/menu/src/main.menu.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
<link rel="stylesheet" type="text/css" href="/assets/css/utilities.css">
<link rel="stylesheet" type="text/css" href="/assets/css/colors.css">
<link rel="stylesheet" type="text/css" href="/assets/css/colors-gh.css">
<link rel="stylesheet" type="text/css" href="/assets/css/colors-g.css">

<!-- CAROUSEL -->
<link rel="stylesheet" href="/assets/vendors/owl.carousel/owl.carousel.min.css">
<link rel="stylesheet" href="/assets/vendors/owl.carousel/owl.theme.default.min.css">

<!-- ANIMATE -->
<link rel="stylesheet" type="text/css" href="/assets/vendors/animate/animate.css">

<!-- ANIMATED HEADLINES -->
<link rel="stylesheet" type="text/css" href="/assets/vendors/animated-headline/css/style.css">

<!-- FANCY BOX -->
<link rel="stylesheet" type="text/css" href="/assets/vendors/fancybox/jquery.fancybox.min.css">

<style>
    body,
    html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: darkcyan !important;
        color: cornsilk;
    }
</style>
{% endblock %}
{% block content %}
<div class="main-header header-shadow cherry-header">
    <div class="bg-cherry">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <div class="text-white mt-10 text-center--md text-center--sm text-center--xs">
                        Helpline 0123456789
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">

        <div class="main-header-container">

            <div class="logo" data-mobile-logo="/assets/images/logo/new_logo2.jpg"
                data-sticky-logo="/assets/images/logo/new_logo2.jpg">
                <a href="{% url 'Admin:home' %}"><img src="/assets/images/logo/new_logo2.jpg" alt="logo" /></a>
            </div> <!-- /LOGO -->

            <div class="burger-menu">
                <div class="line-menu line-half first-line"></div>
                <div class="line-menu"></div>
                <div class="line-menu line-half last-line"></div>
            </div> <!-- /BURGER MENU -->

            <nav class="main-menu menu-caret menu-hover-2 submenu-top-border submenu-scale">
                <ul>
                    <li class="current-menu"><a href="#">Home</a></li>
                    <li><a href="{% url 'Admin:register' %}">Register</a>
                        <ul>
                            <!-- <li><a href="parkings.html">Parkings</a></li>
                        								<li><a href="booking.html">Booking</a></li>
                        								<li><a href="booking-confirm.html">Booking Confirm</a></li>-->
                            <li><a href="{% url 'Admin:adminregistration' %}">Admin Registration</a></li>
                            <li><a href="{% url 'Admin:userregistration' %}">User Registration</a></li>

                        </ul>
                    </li>
                    <li><a href="{% url 'Admin:register' %}">Login</a>
                        <ul>
                            <!-- <li><a href="parkings.html">Parkings</a></li>
                        														<li><a href="booking.html">Booking</a></li>
                        														<li><a href="booking-confirm.html">Booking Confirm</a></li>-->
                            <li><a href="{% url 'Admin:adminlogin' %}">Admin Login</a></li>
                            <li><a href="{% url 'Admin:userlogin' %}">User Login</a></li>

                        </ul>
                    </li>
                    <li><a href="{% url 'Admin:howitworks' %}">How it Works</a></li>
                    <li><a href="{% url 'Admin:aboutus' %}">About Us</a>
                        <!-- <ul>
								<li><a href="meet-and-greet.html">Meet & Greet</a></li>
								<li><a href="testimonials.html">Testimonials</a></li>
							</ul> -->
                    </li>
                    <!-- <li><a href="blog.html">Complaints</a></li> 
                    <li><a href="{% url 'Admin:faqs' %}">FAQs</a></li>-->
                    <li><a href="{% url 'Admin:contactus' %}">Contact Us</a></li>
                </ul>
            </nav> <!-- NAVIGATION MENU -->

        </div> <!-- /HEADER CONTAINER -->

    </div> <!-- /CONTAINER -->
</div> <!-- /HEADER -->
<hr>
<h1 class="heading1">Admin Login</h1>
<hr>
<div class="row justify-content-md-center">
    <div class="col col-lg-6">
        <div class="form-group">
            <form action="{% url 'Admin:adminlogin' %}" method="POST">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input class="form-control" type="text" name="username" placeholder="enter username">

                <label for="password">Password:</label>
                <input class="form-control" type="password" name="password" placeholder="enter password">
                <p></p>
                <input type="submit" name="" value="login">
            </form>
        </div>
    </div>
</div>
<script src="/assets/js/jquery-3.3.1.min.js"></script>
<script src="/assets/vendors/appear/jquery.appear.min.js"></script>
<script src="/assets/vendors/jquery.easing/jquery.easing.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/vendors/common/common.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<!-- FANCY-BOX -->
<script src="/assets/vendors/fancybox/jquery.fancybox.min.js"></script>

<!-- MENU -->
<script src="/assets/vendors/menu/src/main.menu.js"></script>

<!-- CAROUSEL -->
<script src="/assets/vendors/owl.carousel/owl.carousel.min.js"></script>

<!-- ANIMATED-HEADLINES -->
<script src="/assets/vendors/animated-headline/js/animated-headline.js"></script>

<!-- THEME-CUSTOM -->
<script src="/assets/js/main.js"></script>

<!-- THEME-INITIALIZATION-FILES -->
<script src="/assets/js/theme.init.js"></script>
<script src="/assets/js/custom.js"></script>
{% endblock %}

smartparking/system/templates/system/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <style>
        body,
        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            font-family: "Lato", sans-serif
        }

        .w3-bar,
        h1,
        button {
            font-family: "Montserrat", sans-serif
        }

        .fa-anchor,
        .fa-coffee {
            font-size: 200px
        }
    </style>
</head>

<body>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
</body>

</html>